import { logger } from '../../shared/logger';

export function buildAnalysisPrompt(blobJson: any, workflow: any): string {
  return [
    'You are an expert multimodal analysis assistant. Analyze the provided social media storyboard (images) and JSON metadata to extract factual information into a JSON object.',
    '',
    '### INPUT DATA ###',
    '---- BEGIN blobJson ---',
    `${JSON.stringify(blobJson, null, 2)}`,
    '---- END blobJson ---',
    '',
    '---- BEGIN workflow ---',
    `${JSON.stringify(workflow, null, 2)}`,
    '---- END workflow ---',
    '',
    '### ANALYSIS CONTEXT ###',
    'A storyboard (images) and metadata are provided. **Prioritize visual content as the primary source of truth.** Use metadata (blobJson & workflow) to refine analysis (e.g., location, query). `source` in metadata is the *only* platform indicator.',
    '',
    '### CORE INSTRUCTIONS ###',
    '1. **Analyze all data:** Storyboard images (visuals, text, logos), blobJson, and workflow.',
    '2. **Information Hierarchy:**',
    '    * **1st: Storyboard images.** (on-screen text, branding, scenes).',
    '    * **2nd: Metadata text.** (caption, adminTitle), *only if visuals are ambiguous/insufficient.*',
    '    * **Discrepancy: Visuals overrule metadata text.**',
    '3. **Strict JSON Output:** Adhere to the structure and field rules below.',
    '',
    '### FIELD-BY-FIELD RULES ###',
    '* context: Copy verbatim from blobJson.context. Structure: {"l":"city", "cc":"country_code", "w":"search_query"}.',
    '* _id, mediaId, source, permalink: Copy directly from blobJson. source is the only platform field.',
    '* username: From blobJson.username or extract from permalink.',
    '* createdAt, updatedAt, date: Date strings. Use "" if unknown/undetermined, not null.',
    '* mediaType: "video", "carousel", "image", or "other".',
    '* adminTitle:',
    '    * If blobJson.adminTitle exists, optimize to <10 words, SEO-friendly, prioritizing query keywords.',
    '    * If missing/empty, generate compelling, <10 words, accurately summarizing subject, leveraging query keywords.',
    '* slug: URL-friendly. From adminTitle + mediaId (e.g., "A Cool Place! 123" -> "a-cool-place-123"). Fallback: from permalink.',
    '* caption: From blobJson.caption or fallback to adminTitle. Tidy: remove excess whitespace, line breaks, emojis, redundant punctuation, slogans, external links. Focus on clean narrative.',
    '* mediaDescription: Long, objective, detailed summary of distinct visual elements and actions in storyboard images. Only what is seen. No opinions or subjective interpretations.',
    '    * Identified Places (specific, bookable venues/businesses: hotels, restaurants, etc.):',
    '        * Priority 1: Clear visual name/logo. (e.g., sign, cup, storefront). Assign high confidence.',
    '        * Priority 2: Contextual refinement. Use context (location, country, query) for disambiguation/confirmation.',
    '        * Priority 3: Textual fallback. (caption, adminTitle).',
    '        * For each: name (string), confidence (float 0.0-1.0; 1.0 for visual certainty).',
    '    * Identified Locations (well-known, non-bookable public points/landmarks: city squares, bridges, parks, mountains):',
    '        * Priority 1: Clear visual identification.',
    '        * Priority 2: Contextual refinement.',
    '        * Priority 3: Textual fallback.',
    '        * For each: name (string), confidence (float 0.0-1.0; 1.0 for visual certainty).',
    '* Default Values: If a field value cannot be determined and no specific rule applies, use null. Do not invent info.',
    '',
    '### CRITICAL OUTPUT FORMAT RULES ###',
    '* Format: Single, valid JSON object.',
    '* No Extra Text: No preambles, explanations, comments.',
    '* Validity: No trailing commas. Correctly quoted/escaped strings.',
    '* Indentation: 2-space.',
    '',
    '### EXAMPLE OUTPUT ###',
    '{"_id":"media_98765","mediaId":"v54321","source":"instagram","permalink":"https://www.instagram.com/p/CXYZUVW/london_places/","username":"londonwanderer","createdAt":"2023-10-26T10:30:00Z","date":"2023-10-26","adminTitle":"Exploring London\'s Historic Tower Bridge Area","caption":"Had such an amazing day near #TowerBridge in London! Definitely recommend this area for families. #London #FamilyFun #UK #Travel @TowerBridge @TheShardLondon.","mediaDescription":"this video shows a family walking near Tower Bridge in London, with views of the Shard in the background. The area is bustling with tourists and locals enjoying the sunny day.","context":{"l":"London","cc":"GB","w":"London attractions, family fun"}}',
  ].join('\n');
}
