import { logger } from '../../shared/logger';

/**
 * Constructs a prompt for an AI to analyze media metadata (blobJson) and extract a structured JSON object.
 * This function defines the rules for extracting fields like captions, descriptions, locations, and other contextual data.
 *
 * @param blobJson - The primary media data object.
 * @param workflow - Additional context for the analysis task.
 * @returns A formatted string prompt for the AI.
 */
export function buildAnalysisPrompt(blobJson: any, workflow: any): string {
  return [
    '* **title**: (string) The main title for this media, suitable for display as the page or tab header if shown on a website. Use blobJson.adminTitle if present, otherwise fallback to a concise, descriptive title derived from the content.',
    'You are a highly intelligent AI assistant specialized in analyzing media content and extracting structured data based on a specific JSON schema.',
    'Your task is to analyze the provided media data (blobJson) and workflow context to generate a single, valid JSON object. Follow the rules for each field precisely.',
    '',
    '### INPUT DATA ###',
    '--- BLOB JSON ---',
    JSON.stringify(blobJson, null, 2),
    '--- END BLOB JSON ---',
    '',
    '--- WORKFLOW CONTEXT ---',
    JSON.stringify(workflow, null, 2),
    '--- END WORKFLOW CONTEXT ---',
    '',
    '### FIELD DEFINITIONS & RULES ###',
    '* **caption**: From blobJson.caption or fallback to title. Tidy: remove excess whitespace, line breaks, emojis, redundant punctuation, slogans, external links. Focus on clean narrative.',
    '* **slug**: (string) Unique field identifier for later web browsing, generated by combining a URL-friendly version of the title (caption or title) and the media-id (from blobJson.mediaId or id). Use lowercase, hyphens for spaces, and remove special characters. Example: "tower-bridge-london-12345".',
    '* **mediaDescription**: Long, objective, detailed summary of distinct visual elements and actions in storyboard images. Only what is seen. No opinions or subjective interpretations Made of Ai, not human consumption later - Use key terms which can help to classify the video later in a knowledge graph',
    '* **likeCount**: (number) Copy directly from blobJson.If not present or invalid, use null.',
    '* **viewCount**: (number) Copy directly from blobJson. If not present or invalid, use null.',
    '* **places**: (array of objects) Specific, bookable venues or businesses (e.g., hotels, restaurants, museums, shops, bars, cafes, theaters, etc.). Do not include bridges, towers, or general landmarks here. Each object must have:',
    '    * **name**: (string) The name of the place.',
    '    * **confidence**: (float 0.0-1.0) Confidence score; 1.0 for visual certainty.',
    '    * **Prioritization**: Clear visual name/logo (e.g., sign, cup, storefront) > Contextual refinement (using blobJson context, query) > Textual fallback (caption, title).',
    '* **locations**: (array of objects) Well-known, non-bookable landmarks or places of tourism interest (e.g., bridges, towers, monuments, natural formations, famous parks, mountains, historic sites). Do not include cities, countries, or regions. Each object must have:',
    '    * **name**: (string) The name of the location.',
    '    * **confidence**: (float 0.0-1.0) Confidence score; 1.0 for visual certainty.',
    '    * **Prioritization**: Clear visual identification > Contextual refinement (using blobJson context, query) > Textual fallback (caption, title).',
    '* **context**: (object) Provides high-level geographic and keyword context. **IMPORTANT: The values for this object are provided in the WORKFLOW CONTEXT and MUST be copied directly.**',
    '    * **l**: (string) **CRITICAL RULE:** Copy this value **directly** from the `workflow.l` field in the WORKFLOW CONTEXT input. **DO NOT** derive, infer, or change this value based on your analysis of the blobJson.',
    '    * **cc**: (string) **CRITICAL RULE:** Copy this value **directly** from the `workflow.cc` field in the WORKFLOW CONTEXT input. **DO NOT** derive, infer, or change this value.',
    '    * **w**: (string) **CRITICAL RULE:** Copy this value **directly** from the `workflow.w` field in the WORKFLOW CONTEXT input. **DO NOT** create a new list of keywords.',
    '* **Default Values**: If a field value cannot be determined and no specific rule applies, use null. Do not invent info.',
    '',
    '### CRITICAL OUTPUT FORMAT RULES ###',
    '* **Format**: Single, valid JSON object.',
    '* **No Extra Text**: No preambles, explanations, or comments.',
    '* **Validity**: No trailing commas. Correctly quoted/escaped strings.',
    '* **Indentation**: 2-space.',
    '',
    '### EXAMPLE OUTPUT ###',
    // Note: The example provided in the prompt is illustrative and may not match the fields requested above. The AI should prioritize the "FIELD DEFINITIONS & RULES" section.
    '{',
    '  "title": "Tower Bridge Family Day",',
    '  "slug": "tower-bridge-family-day-12345",',
    '  "caption": "Had such an amazing day near Tower Bridge in London! Definitely recommend this area for families.",',
    '  "mediaDescription": [',
    '    "A family walking near Tower Bridge in London, with views of the Shard in the background.",',
    '    "The area is bustling with tourists and locals enjoying the sunny day."',
    '  ],',
    '  "likeCount": 15230,',
    '  "viewCount": 876543,',
    '  "places": [',
    '    { "name": "The Ivy Tower Bridge", "confidence": 1.0 },',
    '    { "name": "Coppa Club", "confidence": 0.95 }',
    '  ],',
    '  "locations": [',
    '    { "name": "Tower Bridge", "confidence": 1.0 },',
    '    { "name": "The Shard", "confidence": 0.9 }',
    '  ],',
    '  "context": {',
    '    "l": "Tower Bridge",',
    '    "cc": "GB",',
    '    "w": [Things to do in London]',
    '  }',
    '}',
  ].join('\n');
}

/**
 * Constructs a prompt for an AI to extract basic venue information from a payload.
 * This function targets the address, postcode, and room types (if applicable).
 *
 * @param payload - The object containing venue data, typically as `payload.venue`.
 * @returns A formatted string prompt for the AI.
 */
export function buildVenueBasicsPrompt(payload: any, workflow?: any): string {
  return [
    'You are an expert at extracting structured information from venue data.',
    '',
    'Given the following payload (which may contain a venue object as payload.venue), extract:',
    '- The venue name (as complete as possible) from the venue data',
    '- The full address (as a single string, as complete as possible) from the venue data',
    '- The postcode (if present) from the venue data',
    '- If the venue is a hotel, also extract a list of room types (e.g., Single, Double, Suite, etc.)',
    '',
    'Return a JSON object with these fields:',
    '{',
    '  "name": string,',
    '  "address": string,',
    '  "postcode": string,',
    '  "roomTypes"?: string[]',
    '}',
    '',
    '--- PAYLOAD ---',
    JSON.stringify(payload, null, 2),
    '--- END PAYLOAD ---',
    '',
    workflow ? '--- WORKFLOW CONTEXT ---' : '',
    workflow ? JSON.stringify(workflow, null, 2) : '',
    workflow ? '--- END WORKFLOW CONTEXT ---' : '',
    '',
    'If a field cannot be determined, use an empty string or empty array as appropriate.',
  ].filter(Boolean).join('\n');
}